import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { fontHeading, fontSans } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontHeading.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
